package com.maintaintrack.models;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Alert — represents a single system alert generated by the AlertService.
 *
 * Day 15: Alert model with type · severity · timestamp
 *
 * type:     OVERDUE_MAINTENANCE | LOW_STOCK
 * severity: HIGH | MEDIUM | LOW
 * refId:    the equipment.id or part.id that triggered this alert
 */
public class Alert {

    public enum Type     { OVERDUE_MAINTENANCE, LOW_STOCK }
    public enum Severity { HIGH, MEDIUM, LOW }

    private final Type          type;
    private final Severity      severity;
    private final String        title;
    private final String        detail;
    private final int           refId;       // equipment or part id
    private final LocalDateTime timestamp;

    private static final DateTimeFormatter FMT =
            DateTimeFormatter.ofPattern("dd MMM HH:mm");

    // ── Constructor ───────────────────────────────────────────────────────

    public Alert(Type type, Severity severity, String title, String detail, int refId) {
        this.type      = type;
        this.severity  = severity;
        this.title     = title;
        this.detail    = detail;
        this.refId     = refId;
        this.timestamp = LocalDateTime.now();
    }

    // ── Getters ───────────────────────────────────────────────────────────

    public Type          getType()      { return type; }
    public Severity      getSeverity()  { return severity; }
    public String        getTitle()     { return title; }
    public String        getDetail()    { return detail; }
    public int           getRefId()     { return refId; }
    public LocalDateTime getTimestamp() { return timestamp; }

    public String getTimestampFormatted() {
        return timestamp.format(FMT);
    }

    /**
     * Icon for display in the dashboard feed.
     * Day 16: colour-coded alerts visible on home screen.
     */
    public String getIcon() {
        return type == Type.OVERDUE_MAINTENANCE ? "🔧" : "📦";
    }

    /**
     * CSS style class for severity colouring.
     * Used by IssueController's alert list cells.
     */
    public String getSeverityStyle() {
        return switch (severity) {
            case HIGH   -> "-fx-text-fill: #8b1a1a; -fx-font-weight: bold;";
            case MEDIUM -> "-fx-text-fill: #b85c00; -fx-font-weight: bold;";
            case LOW    -> "-fx-text-fill: #5c6b8a;";
        };
    }

    @Override
    public String toString() {
        return "[" + severity + "] " + title + " — " + detail;
    }
}
