# Server
server.port=8080

# Database ? fill these in after Supabase setup
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

# App name
spring.application.name=maintaintrack-api

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT
jwt.secret=${JWT_SECRET:MaintainTrackSuperSecretKeyForJWTSigning2026MustBe256BitsLong!!}
jwt.expiry-ms=${JWT_EXPIRY_MS:28800000}

spring.security.user.name=disabled
spring.security.user.password=disabled

